spring:
  application:
    name: entire-pool

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/db_entirepool?currentSchema="q_eco_d_epool"}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:q_eco_d_epool}
    password: ${POSTGRES_PASSWORD:q_eco_d_epool_pwd}
    hikari:
      minimum-idle: ${DB_POOL_MINIMUM_IDLE:1}
      maximum-pool-size: ${DB_POOL_MAXSIZE:10}
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
